"""Named alpha contract versions exposed to adopting projects."""

GOBLIN_CONTAINER_CONTRACT_VERSION = "goblin-king/v1alpha1"
PROJECT_CONFIG_API_VERSION = "goblin-king/v1alpha1"
PROJECT_CONFIG_KIND = "GoblinProject"
API_SETTINGS_SCHEMA_VERSION = "goblin-king/v1alpha1"
REGISTRY_SCHEMA_VERSION = "goblin-king/v1alpha1"
WORKER_IMAGE_MAP_SCHEMA_VERSION = "goblin-king/v1alpha1"
WORKER_RESULT_CONTRACT_VERSION = "goblin-king/v1alpha1"
WORKER_HEARTBEAT_CONTRACT_VERSION = "goblin-king/v1alpha1"
WORKER_RUN_EVENT_CONTRACT_VERSION = "goblin-king/v1alpha1"

__all__ = [
    "API_SETTINGS_SCHEMA_VERSION",
    "GOBLIN_CONTAINER_CONTRACT_VERSION",
    "PROJECT_CONFIG_API_VERSION",
    "PROJECT_CONFIG_KIND",
    "REGISTRY_SCHEMA_VERSION",
    "WORKER_HEARTBEAT_CONTRACT_VERSION",
    "WORKER_RUN_EVENT_CONTRACT_VERSION",
    "WORKER_IMAGE_MAP_SCHEMA_VERSION",
    "WORKER_RESULT_CONTRACT_VERSION",
]
