{{- if and .Values.admin.enabled .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goblin-king.fullname" . }}-admin
  {{- with .Values.admin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.admin.ingress.className }}
  ingressClassName: {{ .Values.admin.ingress.className }}
  {{- end }}
  {{- with .Values.admin.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.admin.ingress.host }}
      http:
        paths:
          - path: /admin
            pathType: {{ .Values.admin.ingress.pathType }}
            backend:
              service:
                name: {{ include "goblin-king.fullname" . }}-admin
                port:
                  number: {{ .Values.admin.port }}
          - path: /admin-api
            pathType: {{ .Values.admin.ingress.pathType }}
            backend:
              service:
                name: {{ include "goblin-king.fullname" . }}-admin
                port:
                  number: {{ .Values.admin.port }}
          - path: /admin-ws
            pathType: {{ .Values.admin.ingress.pathType }}
            backend:
              service:
                name: {{ include "goblin-king.fullname" . }}-admin
                port:
                  number: {{ .Values.admin.port }}
          - path: {{ .Values.admin.ingress.path }}
            pathType: {{ .Values.admin.ingress.pathType }}
            backend:
              service:
                name: {{ include "goblin-king.fullname" . }}-api
                port:
                  number: {{ .Values.api.port }}
{{- end }}
