apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goblin-king.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: {{ include "goblin-king.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/name: {{ include "goblin-king.name" . }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goblin-king.fullname" . }}-redis
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: {{ include "goblin-king.name" . }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
