{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goblin-king.serviceAccountName" (dict "root" . "component" "api") }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "goblin-king.fullname" . }}-api
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "goblin-king.fullname" . }}-api
subjects:
  - kind: ServiceAccount
    name: {{ include "goblin-king.serviceAccountName" (dict "root" . "component" "api") }}
  {{- if .Values.repository.enabled }}
  - kind: ServiceAccount
    name: {{ include "goblin-king.serviceAccountName" (dict "root" . "component" "repository") }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "goblin-king.fullname" . }}-api
{{- if and .Values.admin.enabled .Values.admin.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goblin-king.serviceAccountName" (dict "root" . "component" "admin") }}
  {{- with .Values.admin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.repository.enabled .Values.repository.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goblin-king.serviceAccountName" (dict "root" . "component" "repository") }}
  {{- with .Values.repository.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.repositoryUi.enabled .Values.repositoryUi.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goblin-king.repositoryUiServiceAccountName" . }}
  {{- with .Values.repositoryUi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
